/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package smartthings;

import ratpack.core.server.RatpackServer;
import smartthings.controller.*;

public class App {
    public static void main(String...args) throws Exception {
        UserController userController = new UserController();
        DeviceController deviceController = new DeviceController();
        UserDeviceController userDeviceController = new UserDeviceController();
        RatpackServer.start(server -> {
            server.serverConfig(serverConfig -> serverConfig.port(13004));
            server.handlers(chain -> chain
                .path("api/user", ctx -> ctx
                    .byMethod(m -> m
                        .post(() -> userController.createUser(ctx))
                    )
                )
                .path("api/login", ctx -> ctx
                    .byMethod(m -> m
                        .post(() -> userController.login(ctx))
                    )
                )
                .path("api/device", ctx -> ctx
                    .byMethod(m -> m
                        .post(() -> deviceController.createDevice(ctx))
                        .get(() -> deviceController.getAllDevices(ctx))
                        .delete(() -> deviceController.deleteDevice(ctx))
                        .put(() -> deviceController.updateDevice(ctx))
                    )
                )
                .path("api/user/device", ctx -> ctx
                    .byMethod(m -> m
                        .post(() -> userDeviceController.registerDevice(ctx))
                        .delete(() -> userDeviceController.unregisterDevice(ctx))
                        .get(() -> userDeviceController.getRegisteredDevices(ctx))
                        .put(() -> userDeviceController.updateDeviceValue(ctx))
                    )
                )
                .path("api/user/device/available", ctx -> ctx
                    .byMethod(m -> m
                        .get(() -> userDeviceController.getAvailableDevices(ctx))
                    )
                )
                .path("api/admin/getUser", ctx -> ctx
                    .byMethod(m -> m
                        .get(() -> userController.getUser(ctx))
                    )
                )
                .path("api/admin/getUsers", ctx -> ctx
                    .byMethod(m -> m
                        .get(() -> userController.getUsers(ctx))
                    )
                )
            );
        });
    }
}